















# ─────────────── BASIC IO ─────────────────
data_file: "/home/cheddarjackk/Developer/project_root/filter/data/oscillator_learning_set.parquet"
model_out: "/home/cheddarjackk/Developer/project_root/filter/filter_model.joblib"

# ───────────────   TASK   ─────────────────
target_pnl: "pnl"     # column name whose sign defines win/loss
test_split: 0.15      # last 15 % of rows reserved for out-of-sample
min_kept: 100          # minimum trades the filter must keep

# ───────────── THRESHOLD GRID ─────────────
proba_thresholds:     # probability cut-offs we’ll scan
  - 0.05
  - 0.10
  - 0.15
  - 0.20
  - 0.25
  - 0.30
  - 0.35
  - 0.40
  - 0.45
  - 0.50
  - 0.55
  - 0.60
  - 0.65
  - 0.70
  - 0.75
  - 0.80
  - 0.85
  - 0.90
  - 0.95

# ─────────────── MODEL CHOICE ─────────────
model_type: "random_forest"   # "lightgbm" | "xgboost" | "random_forest" | "gbm_sklearn" | "log_reg"

# ───────────── HYPER-PARAMETERS ───────────
# NEW model default sections so every search param exists in YAML
hyper:
  lightgbm:
    n_estimators: 600
    learning_rate: 0.05
    max_depth: 8
    num_leaves: 31
    feature_fraction: 0.9
    bagging_fraction: 0.9
    min_gain_to_split: 0.0
    is_unbalance: true
    random_state: 42

  xgboost:
    n_estimators: 1200
    eta: 0.03
    max_depth: 6
    subsample: 0.9
    colsample_bytree: 0.9
    gamma: 0
    random_state: 42

  hist_gbm:
    learning_rate: 0.05
    max_depth: 8
    max_iter: 800

  extra_trees:
    n_estimators: 1000
    max_depth: 20
    min_samples_leaf: 4
    random_state: 42

  ada_boost:
    n_estimators: 500
    learning_rate: 0.1
    random_state: 42

  random_forest:
    n_estimators: 1200
    max_depth: 20
    min_samples_leaf: 4
    class_weight: balanced
    random_state: 42

  linear_svm:
    C: 1.0

  naive_bayes: {}

  knn:
    n_neighbors: 7
    weights: uniform
    metric: euclidean

  log_reg:
    C: 1.0
    max_iter: 4000
    solver: lbfgs
    class_weight: balanced



# Trial 41 finished with value: 0.295455 and parameters: {'model': 'xgboost', 'xgb_n': 2200, 'xgb_lr': 0.06413396980519909, 'xgb_md': 8, 'xgb_sub': 0.5744870807703321, 'xgb_col': 0.9476492932080297, 'xgb_gam': 1.479665584485633}. Best is trial 41 with value: 0.295455.